### PR TITLE
Allows "Use Double Hook" and "Use Triple Hook" to be enabled simultaneously

### PR DESCRIPTION
**Pull request by Nheat**
Mentioned in #68 and it's something I wanted as well, seemed simple enough. Will prioritize Triple Hook.

### CODE REVIEW

**Comment by InitialDet** [comment]
This was discussed before on #63, enabling both at the same time doest make sense because triple hook would never be used outside the first hook.

**Comment by Nheat** [comment]
Unless you are aiming for a particular fish and can easily identify it, like grinding Sweatfish in the Diadem. If I'm at 600 GP and get a bite and my Hi-Cordial is about to come off cooldown, I'd rather waste ~50 GP with a less efficient hook than let it go (or single hook, depending on if Prize Catch is being used). And then end up overcapping on GP or delaying my Hi-Cordial.

**Comment by InitialDet** [comment]
Thats the thing, it'll basically always use Double Hook as long youre below 700gp. I cant see a scenario where you can build 700 gp to use Triple Hook while Double Hook is also activated.

**Comment by Nheat** [comment]
Unlucky streaks building up GP over time, Hi-Cordial and Thaliak's Favor giving bursts of GP. I'm 200k skyward points in and it happens more than you'd think.

**Comment by InitialDet** [comment]
Fair enough, I'll be doing a slightly different implementation so i'll be closing this PR, but thank you nonetheless.

**Comment by Nheat** [comment]
No problem, sorry if our little back and forth was a pain.

**Comment by InitialDet** [comment]
No problem at all, i was just hesitant about this before but i guess its fine if people really want it. That being said, you'll need to hold shift to enable both options, because i still believe its better to either go only double or only triple hook.

**Comment by InitialDet** [comment]
The new version should be available in a few minutes

**Pull request closed without merging**
